" This vimrc is based on LLVM TEAM's vimrc

" LLVM coding guidelines conformance for VIM
" $Revision$
"
" Maintainer: The LLVM Team, http://llvm.org
" WARNING:    Read before you source in all these commands and macros!  Some
"             of them may change VIM behavior that you depend on.
"
" You can run VIM with these settings without changing your current setup with:
" $ vim -u /path/to/llvm/utils/vim/vimrc

" It's VIM, not VI
set nocompatible

" plugins which managed by vundle
filetype off

set rtp+=$FENV_GIT/vim/vim/vundle/
call vundle#rc("$FENV_HOME/vim/")

source $FENV_HOME/vim/nerdtree.vimrc
source $FENV_HOME/vim/powerline.vimrc
source $FENV_HOME/vim/taglist.vimrc
source $FENV_HOME/vim/cscope.vimrc
source $FENV_HOME/vim/youcompleteme.vimrc
source $FENV_HOME/vim/syntastic.vimrc
source $FENV_HOME/vim/easymotion.vimrc
source $FENV_HOME/vim/ctrlp.vimrc

filetype plugin indent on

source $FENV_HOME/vim/generic.vimrc
