FROM finaldie/dev-base:latest

# ------------------------ ccls (C/C++) ---------------------------------------
RUN set -ex; \
    git clone --depth 1 --recurse-submodules -j8 \
        git://github.com/MaskRay/ccls.git /build/ccls \
    && cd /build/ccls \
    && cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_CXX_COMPILER=clang++ \
    && cmake --build Release \
    && cp /build/ccls/Release/ccls /usr/local/bin \
    && cd / \
    && rm -rf /build/ccls
