# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/final/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# fenv zshrcs
[[ ! -f ~/.zsh/fenv.zsh ]] || source ~/.zsh/fenv.zsh

# Enable powerlevel10k theme
[[ ! -f ~/.zsh/p10k.zsh-theme ]] || source ~/.zsh/p10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.zsh/p10k.zsh ]] || source ~/.zsh/p10k.zsh

# FZF key-binding and completion
[[ ! -f ~/.zsh/fzf-key-bindings.zsh ]] || source ~/.zsh/fzf-key-bindings.zsh
[[ ! -f ~/.zsh/fzf-completion.zsh ]] || source ~/.zsh/fzf-completion.zsh

# Tmuxinator completion
[[ ! -f ~/.zsh/tmuxinator.zsh ]] || source ~/.zsh/tmuxinator.zsh

# [Plugin] zsh-autosuggestions
[[ ! -f ~/.zsh/zsh-autosuggestions.zsh ]] || source ~/.zsh/zsh-autosuggestions.zsh

## To speed up autosuggestions plugin (otherwise user will notice a big lag on
## every prompt)
typeset -g ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
typeset -g ZSH_AUTOSUGGEST_USE_ASYNC=1
typeset -g ZSH_AUTOSUGGEST_MANUAL_REBIND=1

# User local zshrc
[[ ! -f ~/.zsh/user.zsh ]] || source ~/.zsh/user.zsh

# [Plugin] zsh-syntax-highlighting (Keep it at the bottom)
[[ ! -f ~/.zsh/zsh-syntax-highlighting.zsh ]] || source ~/.zsh/zsh-syntax-highlighting.zsh
