# TMUX
if which tmux >/dev/null 2>&1; then
  ID="$(tmux ls | head -1 | cut -d: -f1 )" # get the id of the first one

  if [[ -z "$ID" ]]; then # if not available create a new one
    tmux new-session
  else
    tmux attach-session -t "$ID" # if available attach to it
  fi
fi

if [ -f ~/.bash/fenv.bash ]; then
    source ~/.bash/fenv.bash
fi

# FZF binding
if [ -f ~/.bash/fzf-key-bindings.bash ]; then
  source ~/.bash/fzf-key-bindings.bash
fi

if [ -f ~/.bash/fzf-completion.bash ]; then
  source ~/.bash/fzf-completion.bash
fi

# Tmuxinator
if [ -f ~/.bash/tmuxinator.bash ]; then
  source ~/.bash/tmuxinator.bash
fi

# User local bashrc (Keep it at bottom)
if [ -f ~/.bash/user.bash ]; then
  source ~/.bash/user.bash
fi
