# TMUX
if which tmux >/dev/null 2>&1; then
  #if not inside a tmux session, and if no session is started, start a new session
  test -z "$TMUX" && (exec tmux attach || exec tmux new-session)
fi

if [ -f ~/.bash/fenv.bash ]; then
    source ~/.bash/fenv.bash
fi

# FZF binding
if [ -f ~/.bash/fzf-key-bindings.bash ]; then
  source ~/.bash/fzf-key-bindings.bash
fi

if [ -f ~/.bash/fzf-completion.bash ]; then
  source ~/.bash/fzf-completion.bash
fi

# Tmuxinator
if [ -f ~/.bash/tmuxinator.bash ]; then
  source ~/.bash/tmuxinator.bash
fi

# User local bashrc (Keep it at bottom)
if [ -f ~/.bash/user.bash ]; then
  source ~/.bash/user.bash
fi
